###
POST http://localhost:4001/auth/signup
Content-Type: application/json

{
  "username": "username",
  "password": "password",
  "email": "email@email.com"
}

###
POST http://localhost:4001/auth/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

###

POST http://localhost:4001/auth/logout
Content-Type: application/json

{
  "token": ""
}

###
POST http://localhost:4001/auth/token
Content-Type: application/json

{
  "token": ""
}

###

GET http://localhost:4001/auth/verify?token=""

###

POST http://localhost:4001/auth/forget-password
Content-Type: application/json

{
  "username": "username"
}

###

POST http://localhost:4001/auth/reset-password
Content-Type: application/json

{
  "username": "username",
  "password": "",
  "token": ""
}

###

POST http://localhost:4001/social/login-url
Content-Type: application/json

{
  "key":  "GITHUB"
}

###

POST http://localhost:4001/social/login
Content-Type: application/json

{
  "key":  "GITHUB",
  "code": "code",
  "state": "state"
}

###

POST http://localhost:4001/social/login-with-access-token
Content-Type: application/json

{
  "key":  "GITHUB",
  "accessToken": "",
  "tokenType": "Bearer"
}

###

GET http://localhost:4001/info/me
Content-Type: application/json
Authorization: Bearer token

###
