###
POST http://localhost:4000/auth/signup
Content-Type: application/json

{
  "username": "username",
  "password": "password",
  "email": "email@email.com"
}

###
POST http://localhost:4000/auth/login
Content-Type: application/json

{
  "username": "username",
  "password": "password"
}

###

POST http://localhost:4000/auth/logout
Content-Type: application/json

{
  "token": ""
}

###
POST http://localhost:4000/auth/token
Content-Type: application/json

{
  "token": ""
}

###

GET http://localhost:4000/auth/verify?token=""

###

POST http://localhost:4000/auth/forget-password
Content-Type: application/json

{
  "username": "username"
}

###

POST http://localhost:4000/auth/reset-password
Content-Type: application/json

{
  "username": "username",
  "password": "",
  "token": ""
}

###
