###
POST http://localhost:4001/auth/signup
Content-Type: application/json

{
 "username": "username_test",
 "password": "password",
 "email": "furkanyavuz.spambox@gmail.com"
}

###
POST http://localhost:4001/auth/login
Content-Type: application/json

{
 "username": "username_test",
 "password": "password"
}

###

POST http://localhost:4001/auth/logout
Content-Type: application/json

{
 "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lX3Rlc3QiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTU5OTk0MzAzNywiZXhwIjoxNTk5OTQzOTM3fQ.SCGsWKxE3UJ__wqv3gxrWsEHreqd-5n_qaOwuZJySQk"
}

###
POST http://localhost:4001/auth/token
Content-Type: application/json

{
 "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lX3Rlc3QiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTU5OTk0MzE3NywiZXhwIjoxNjAyNTM1MTc3fQ.oAD_AggGsqoPVp4SiLNVCVlXSjzk3-pTns4onvQKhSU"
}

###

GET http://localhost:4001/auth/verify?token=token

###

POST http://localhost:4001/auth/forget-password
Content-Type: application/json

{
 "username": "furkan"
}

###

POST http://localhost:4001/auth/reset-password
Content-Type: application/json

{
 "username": "username",
 "password": "password",
 "token": "token"
}
