###
POST http://localhost:4001/auth/signup
Content-Type: application/json

{
 "username": "username",
 "password": "password",
 "email": "email@email.com"
}

###
POST http://localhost:4001/auth/login
Content-Type: application/json

{
 "username": "furkan",
 "password": "qwe123"
}

###

POST http://localhost:4001/auth/logout
Content-Type: application/json

{
 "token": "token"
}

###
POST http://localhost:4001/auth/token
Content-Type: application/json

{
 "token": "token"
}

###

GET http://localhost:4001/auth/verify?token=token

###

POST http://localhost:4001/auth/forget-password
Content-Type: application/json

{
 "username": "username"
}

###

POST http://localhost:4001/auth/reset-password
Content-Type: application/json

{
 "username": "username",
 "password": "password",
 "token": "token"
}
