### Get Social Login URL
POST http://localhost:4001/social/login-url
Content-Type: application/json

{
  "key": "GITHUB"
}

### Social Login
POST http://localhost:4001/social/login
Content-Type: application/json

{
  "key": "GITHUB",
  "code": "code",
  "state": "state"
}

### Social Login With Access token
POST http://localhost:4001/social/login-with-access-token
Content-Type: application/json

{
  "key": "GITHUB",
  "accessToken": "",
  "tokenType": "Bearer"
}
