### Team Create
POST http://localhost:4001/team
Content-Type: application/json

{
}

### Verify team
POST  http://localhost:4001/team/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lcnQiLCJyb2xlIjoiQURNSU4iLCJ0ZWFtcyI6W3siX2lkIjoiNjM5NTI3MjQ2OGE3M2MzODBiMzVlMGU1IiwiaWQiOiI2Mzk1MjcyNDY4YTczYzM4MGIzNWUwZTQiLCJuYW1lIjoiTWVydCdzIHRlYW0yIiwiY3JlYXRvciI6Im1lcnQiLCJ3cml0ZXJzIjpbXSwicmVhZGVycyI6W10sIl9fdiI6MH0seyJpZCI6IjYzOTVjZGIzZjFhMGQ1ZjFhNzMzYTc4OSIsIm5hbWUiOiJNZXJ0J3MgdGVhbSIsImltYWdlSWQiOiI1IiwiY3JlYXRvciI6Im1lcnQiLCJ3cml0ZXJzIjpbXSwicmVhZGVycyI6W10sIl9pZCI6IjYzOTVjZGIzZjFhMGQ1ZjFhNzMzYTc4YSIsIl9fdiI6MH1dLCJpYXQiOjE2NzA3NjE5MDksImV4cCI6MzM0MTUyNjk0MH0.PmkFLvVQwTTy3rpT1qM7eZHmVfTHWP0z0ncDpHhNfVI

{   
    "verifyToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1lcnQyIiwidGVhbSI6eyJpZCI6IjYzOTVjZGIzZjFhMGQ1ZjFhNzMzYTc4OSIsInJvbGUiOiJ3cml0ZXJzIn0sImlhdCI6MTY3MDc2MjAzNCwiZXhwIjoxNjcxNjI2MDM0fQ.mR9H3kFxvqa8h-FBkh89Q6qgfehlnfzNcM26DpH1Q50"
}