name: PR Labeled at Develop Workflows

on:
  pull_request:
    types:
      - labeled
    branches:
      - develop

jobs:
  auto-merge:
    name: 'Auto Merge'
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: 'pascalgn/automerge-action@v0.14.3'
        env:
          GITHUB_TOKEN: '${{ secrets.MASTER_BRANCH_ACCESS_TOKEN }}'
          MERGE_LABELS: 'workflow'
          MERGE_COMMIT_MESSAGE: 'Auto merge for PR with workflow label'
          MERGE_FORKS: 'false'
          MERGE_RETRY_SLEEP: '60000'
